function b = CreateBrain;

%% Variables:
leftMotorSignal = 0;
rightMotorSignal = 0;
currentState = 0;
timePoint = 0;
sonarReading = 0;
numberOfSonarReadings = 0;
foundCylinder = 0;
steps = 0;

%% Parameters:
forwardMotorSignal = 0.2;
turnMotorSignal = 0.7;
oneLapTime = 2;


b = struct('LeftMotorSignal',leftMotorSignal,...
           'RightMotorSignal',rightMotorSignal,...
           'CurrentState',currentState,...
           'TimePoint',timePoint,...
           'SonarReading',sonarReading,...
           'NumberOfSonarReadings',numberOfSonarReadings,...
           'FoundCylinder',foundCylinder,...
           'Steps',steps,...
           'ForwardMotorSignal',forwardMotorSignal,...
           'TurnMotorSignal',turnMotorSignal,...
           'OneLapTime',oneLapTime);