function s = CreateLRF(name,size,numberOfRays,openingAngle,range,sigma);

s = struct('Name',name,...
           'Type','IR',...
           'RelativeAngle',0.0,...
           'Size',size,...
           'NumberOfRays',numberOfRays,...
           'OpeningAngle',openingAngle,...
           'Range',range,...
           'Sigma',sigma,...
           'Position',[0 0],...
           'AbsoluteAngle',0,...
           'RayDirections',zeros(numberOfRays,1),...
           'RayLengths',zeros(numberOfRays,1),...
           'Reading',0);
           
